### ISSUE TITLE
[Poposal] - Flatpak

### ISSUE THREAD

**Issue by margual56** [AlexxxRu/TinyPomodoro#11]
Hello! I would like to propose packaging this app as a flatpak and uploading it to flathub maybe.

# Why?
Flatpaks allow easy distribution to any OS without needing to have headaches due to the dependencies and library versions.

It will lower the barrier of entry by not making the users compile the app themselves.

It also make the app more discoverable, since people would be able to see it from their graphic package managers (gnome's software center, KDE's discover, etc).

# Requirements
The assets needed are:
- The manifest file
- An app icon
- A `.desktop` file

## The manifest file
[Documentation](https://docs.flatpak.org/en/latest/manifests.html)
It would look something like this: 
(file name: `org.aliashenko.TinyPomodoro`)
```YAML
app-id: org.aliashenko.TinyPomodoro
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
command: tiny_pomodoro
modules:
  - name: tiny_pomodoro
    buildsystem: simple
    build-commands:
      - install -D tiny_pomodoro /app/bin/tiny_pomodoro
    sources:

      - type: file
        path: tiny_pomodoro
finish-args:
  # Wayland access
  - --socket=wayland
  - --socket=fallback-x11

```

## App icon
Not required, but obviously recommended.

See the proposals: #10 

## .desktop file
It would look something like this:
```desktop
[Desktop Entry]
Name=TinyPomodoro
Exec=flatpak run org.aliashenko.TinyPomodoro
Type=Application
Icon=org.aliashenko.TinyPomodoro
Categories=Utility;Clock;Timer;Office;Studying;
```

_Note: Not sure these are right, please review them_

Thanks!
